### ISSUE TITLE
Consolidate modular code among various efforts

### ISSUE THREAD

**Issue by dpshepherd** [QI2lab/OPM#5]
We should think about how best to consolidate metadata parsing, dataset loading, viewing, and other modular functions between the various efforts going on. There will be some more changes on the acquisition side soon to allow users to set everything up in Micro-manager and hopefully view a computational deskew preview of their FOV to aid setting the microscope up.

Also - I noticed a couple people forked the repo recently. I will make an effort to keep the master branch more in synch with important changes from here on out.

**Comment by ptbrown1729** [comment]
@dpshepherd  @fdjutant  per our discussion at subgroup meeting today:

Current plan for the Galvo branch: all of the code except for the localization code has already been moved to master. Create a new branch from master and add the localization code (at this point Galvo will be defunct). We can use this as a development branch until the localization code is fully vetted, then it will be merged back into master.

We will also make a single file in master for data/metadata loading. I can take a first crack at this, but will need input from everyone to ensure it works for all experiments. This is likely to break some workflows at the beginning.

**Comment by ptbrown1729** [comment]
@dpshepherd @fdjutant I think we can delete the galvo branch now right? No one is using it anymore and the relevant code should be on master or localization

**Comment by fdjutant** [comment]
@ptbrown1729. I agree. I just use the master recently for the recon stuff

**Comment by dpshepherd** [comment]
This looks good and thanks for deleting. The next consolidation effort should be to get an nearly automated pipeline for iterative RNA-FISH localization with coordinate transforms between tiles, channels, and rounds determined using either Python or BigStitcher. I still think BigStitcher does a better job calculating the coordinate transforms, but we can look into other existing Python solutions so that we don't have to make command line calls to BigStitcher. Because BigStitcher can run in FIJI's headless mode, that isn't that hard to include in Python.
