### ISSUE TITLE
BDV XML not created

### ISSUE THREAD

**Issue by dpshepherd** [QI2lab/OPM#7]
@AlexCoul - did the bright and dark fields images get written? If not, then my guess is the program got stuck trying to load data somewhere and failed.

**Comment by dpshepherd** [comment]
I think I know what happened and it has to do with not handling the last round with fewer channels correctly when also reconstruction the FISH channels. I'll make some changes and start the code running again under my account.

**Comment by dpshepherd** [comment]
It worked, but the difference in channels is causing a bit of an issue for stitching. I'll see if there is a work around.

**Comment by AlexCoul** [comment]
Ah I see! I'll think about it too...

Le 16/02/2022 à 14:15, Doug Shepherd a écrit :

**Comment by dpshepherd** [comment]
It is possible to still register correctly, only with channel 1 (alexa488 polyA), using the "batch" commands.

Somehow the deskew was the wrong direction. If you load the file, highlight the views, and press "r", it should center the data in the viewer. You can then press "x" or "y" to look at the XZ or YZ projections. You'll see that the deskew went the wrong way along the scan, but the orthogonal axis is OK.
